### ISSUE TITLE
auto-build the native library as part of pub get"

### ISSUE THREAD

**Issue by robertmuth** [google/dart-glfw#7]

**Comment by jtmcdole** [comment]
We're not going to be able to auto-build the library if you don't have GLFW installed. What we could do is potentially redistribute libglfw and our library for different platforms (linux, windows, etc) and that would get around needing to build the library.

**Comment by rishavs** [comment]
Why can we not install this library by using pub get?

I understand that the glfw dlls themselves may need to be placed manually by the user but that is expected in pretty much every sdl/glfw/sfml bindings.

**Comment by jtmcdole** [comment]
It's been a long time since I've looked at this and I do not know what options are available for auto-build. Adding the .so/.dll files compiled for every supported platform could be done, but I'm not sure the maintainers have a whole lot of time on their hands (I should know, we both work together on other projects).

**Comment by rishavs** [comment]
thats unfortunate. 
Dart simply doesnt seems to have a way of using opengl context without using other languages like go.

**Comment by jtmcdole** [comment]
Natively via the Dart VM? This and I believe Flutter are the only ways you can get access to a GL context. I've recently run this on another project, so I know it's alive and well. We also used this on some embedded devices (hence its existence) and it ran great.
